name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
      - run: npm run build
      - uses: EndBug/add-and-commit@v7
        with:
          add: docs
          force: true
          message: [GitHub Action]: Add test coverage docs
        env:
          GITHUB_TOKEN: $